import type { Service, Software, Review } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getLogo = (type: 'provider' | 'software', index: number) => {
    const id = `${type}-logo-${index + 1}`;
    const image = PlaceHolderImages.find(p => p.id === id);
    return image ? image.imageUrl : `https://picsum.photos/seed/${id}/100/100`;
};

const getAvatar = (index: number) => {
    const id = `avatar-${index + 1}`;
    const image = PlaceHolderImages.find(p => p.id === id);
    return image ? image.imageUrl : `https://picsum.photos/seed/${id}/40/40`;
}

const reviews: Review[] = [
  { id: 'review-1', author: 'John D.', avatarUrl: getAvatar(0), rating: 5, comment: 'Exceptional service and support. Highly recommended!', date: '2023-10-15' },
  { id: 'review-2', author: 'Sarah P.', avatarUrl: getAvatar(1), rating: 4, comment: 'Very effective, though a bit pricey. The results speak for themselves.', date: '2023-09-22' },
  { id: 'review-3', author: 'Mike T.', avatarUrl: getAvatar(2), rating: 3, comment: 'Good, but the onboarding process could be smoother.', date: '2023-11-01' },
];

export const services: Service[] = [
  {
    id: 'marketing-pro-au',
    name: 'Marketing Pro AU',
    category: 'Marketing',
    logoUrl: getLogo('provider', 0),
    tagline: 'Driving growth for Australian brokers.',
    description: 'A full-suite digital marketing agency specializing in lead generation, social media management, and SEO for the finance industry.',
    location: 'Sydney, NSW',
    website: 'https://marketingproau.com',
    reviews: reviews.map(r => ({ ...r, verified: true, helpfulCount: 12 })),
    features: ['Lead Generation Campaigns', 'SEO & Content Marketing', 'Social Media Management', 'PPC Advertising'],
    pricingModel: 'Retainer',
    pricingRange: { min: 1500, max: 5000 },
    serviceAreas: ['Lead Generation', 'SEO', 'Content', 'Social'],
    brokerTypes: ['Mortgage', 'Asset Finance', 'Commercial'],
    badges: ['High Performer'],
    availability: 'Australia-wide',
  },
  {
    id: 'va-connect',
    name: 'VA Connect',
    category: 'Virtual Assistant',
    logoUrl: getLogo('provider', 1),
    tagline: 'Your reliable remote back-office support.',
    description: 'VA Connect provides highly-trained virtual assistants to handle administrative tasks, client communication, and appointment setting for busy brokers.',
    location: 'Melbourne, VIC',
    website: 'https://vaconnect.com',
    reviews: [reviews[1], reviews[2]],
    features: ['Appointment Scheduling', 'Email & Calendar Management', 'Client Follow-ups', 'Data Entry'],
    pricingModel: 'Hourly',
    pricingRange: { min: 20, max: 45 },
    serviceAreas: ['Administration', 'Client Communication'],
    brokerTypes: ['Mortgage'],
    availability: 'Australia-wide',
  },
  {
    id: 'commercial-finance-experts',
    name: 'Commercial Finance Experts',
    category: 'Commercial Finance',
    logoUrl: getLogo('provider', 2),
    tagline: 'Complex deals, simplified.',
    description: 'We partner with brokers to structure and secure complex commercial and development finance deals, providing expertise and access to a wide panel of lenders.',
    location: 'Brisbane, QLD',
    website: 'https://cfexperts.com',
    reviews: [reviews[0]],
    features: ['Deal Structuring', 'Scenario Analysis', 'Access to Private Lenders', 'Development Finance'],
    pricingModel: 'Project-based',
    serviceAreas: ['Deal Structuring', 'Scenario Analysis'],
    brokerTypes: ['Commercial'],
    availability: 'Australia-wide',
  },
   {
    id: 'broker-boost',
    name: 'Broker Boost',
    category: 'Marketing',
    logoUrl: getLogo('provider', 3),
    tagline: 'Amplify your brand and reach.',
    description: 'Specialists in branding and content creation for mortgage brokers, helping you stand out in a crowded market.',
    location: 'Perth, WA',
    website: 'https://brokerboost.com',
    reviews: [reviews[0], reviews[1], reviews[2]],
    features: ['Brand Identity Design', 'Video Marketing', 'Blog & Article Writing', 'Email Newsletters'],
    pricingModel: 'Project-based',
    serviceAreas: ['Branding', 'Content', 'Video'],
    brokerTypes: ['Mortgage', 'Asset Finance'],
    badges: ['Rising Star'],
  },
   {
    id: 'admin-assist-plus',
    name: 'Admin Assist Plus',
    category: 'Virtual Assistant',
    logoUrl: getLogo('provider', 4),
    tagline: 'Focus on what you do best - selling.',
    description: 'Our team of experienced VAs integrates seamlessly with your existing workflow to provide top-tier administrative support.',
    location: 'Adelaide, SA',
    website: 'https://adminassistplus.com',
    reviews: [reviews[1]],
    features: ['Loan Application Support', 'CRM Management', 'Compliance Checks', 'General Admin'],
    pricingModel: 'Retainer',
    pricingRange: { min: 800, max: 2500 },
    serviceAreas: ['Loan Support', 'CRM', 'Compliance'],
    brokerTypes: ['Mortgage'],
  },
];

export const software: Software[] = [
  {
    id: 'broker-crm-x',
    name: 'BrokerCRM X',
    category: 'CRM',
    logoUrl: getLogo('software', 0),
    tagline: 'The all-in-one client relationship platform.',
    description: 'Manage your client pipeline, automate follow-ups, and track commissions with a powerful CRM built specifically for brokers.',
    pricing: 'Starts at $99/month',
    compatibility: ['Xero', 'Zapier', 'Office 365'],
    reviews: reviews.map(r => ({
      ...r,
      userSegment: 'Small Team (2-5)',
      brokerType: 'Mortgage',
      verified: true,
      helpfulCount: 5,
    })),
    features: ['Lead Management', 'Automated Workflows', 'Commission Tracking', 'Reporting Dashboard'],
    pricingTiers: [
      { name: 'Starter', price: '$49/mo', features: ['Leads', 'Basic Workflows'] },
      { name: 'Pro', price: '$99/mo', features: ['Leads', 'Workflows', 'Commissions'] },
      { name: 'Enterprise', price: 'Contact Sales', features: ['Advanced Reporting', 'SSO'] },
    ],
    deployment: 'Cloud',
    supportOptions: ['Email', 'Chat'],
    integrations: [
      { name: 'Xero', category: 'Accounting' },
      { name: 'Zapier', category: 'Other' },
      { name: 'Office 365', category: 'Other' },
    ],
    userSegments: ['Solo Broker', 'Small Team (2-5)', 'Mid-Size (6-20)'],
    marketPresence: { activeUsers: 2500, adoptionRate: 62 },
    badges: ['Leader', 'Best Value'],
    brokerSpecific: { lenderConnections: ['ANZ', 'NAB'], complianceTools: ['BID Tools'], commissionTracking: true },
  },
  {
    id: 'loan-flow-pro',
    name: 'LoanFlow Pro',
    category: 'Loan Processing',
    logoUrl: getLogo('software', 1),
    tagline: 'Streamline your application process.',
    description: 'A dedicated loan processing tool that simplifies document collection, submission, and tracking from application to settlement.',
    pricing: '$75/user/month',
    compatibility: ['ApplyOnline', 'NextGen.Net'],
    reviews: [reviews[0], reviews[2]],
    features: ['Digital Document Collection', 'Lender Portal Integration', 'Automated Status Updates', 'Client Portal'],
    pricingTiers: [
      { name: 'Professional', price: '$75/user/mo', features: ['Docs', 'Portal', 'Status Updates'] },
    ],
    deployment: 'Cloud',
    supportOptions: ['Email', 'Phone'],
    integrations: [{ name: 'ApplyOnline', category: 'Lender' }, { name: 'NextGen.Net', category: 'Lender' }],
    userSegments: ['Small Team (2-5)', 'Mid-Size (6-20)'],
    marketPresence: { activeUsers: 1400, adoptionRate: 48 },
    badges: ['High Performer'],
    brokerSpecific: { lenderConnections: ['CBA', 'Westpac'], complianceTools: [], commissionTracking: false },
  },
  {
    id: 'comply-guard',
    name: 'ComplyGuard',
    category: 'Compliance',
    logoUrl: getLogo('software', 2),
    tagline: 'Compliance made easy.',
    description: 'Stay on top of your regulatory obligations with automated compliance checks, reporting, and audit trail capabilities.',
    pricing: 'Contact for enterprise pricing',
    compatibility: ['BrokerCRM X', 'Salesforce'],
    reviews: [reviews[1]],
    features: ['Best Interest Duty (BID) Tools', 'Automated Disclosure Generation', 'Audit Log', 'CPD Tracking'],
    deployment: 'Cloud',
    supportOptions: ['Email'],
    userSegments: ['Mid-Size (6-20)', 'Large (20+)'],
    badges: ['Rising Star'],
    brokerSpecific: { complianceTools: ['BID', 'CPD'], commissionTracking: false },
  },
  {
    id: 'reach-engine',
    name: 'ReachEngine',
    category: 'Marketing Automation',
    logoUrl: getLogo('software', 3),
    tagline: 'Automate your marketing, grow your client base.',
    description: 'An easy-to-use platform for creating email campaigns, social media posts, and managing your online presence.',
    pricing: 'Starts at $49/month',
    compatibility: ['Facebook', 'LinkedIn', 'Mailchimp API'],
    reviews: [reviews[0], reviews[1]],
    features: ['Email Campaign Builder', 'Social Media Scheduler', 'Lead Capture Forms', 'Analytics'],
    pricingTiers: [
      { name: 'Starter', price: '$49/mo', features: ['Email', 'Social Scheduler'] },
      { name: 'Pro', price: '$79/mo', features: ['Lead Forms', 'Analytics'] },
    ],
    deployment: 'Cloud',
    supportOptions: ['Email', 'Chat'],
    integrations: [{ name: 'Mailchimp', category: 'Marketing' }, { name: 'Facebook', category: 'Marketing' }],
    userSegments: ['Solo Broker', 'Small Team (2-5)'],
    marketPresence: { activeUsers: 3200, adoptionRate: 55 },
    badges: ['Most Popular'],
  },
];
